Cargo.lock, Cargo.toml, crates/interface-blobstore/Cargo.toml, crates/interface-blobstore/src/lib.rs, crates/interface-http/Cargo.toml, crates/interface-http/src/lib.rs, crates/interface-keyvalue/Cargo.toml, crates/interface-keyvalue/src/lib.rs, crates/runtime-wasmtime/Cargo.toml, crates/transport-nats/Cargo.toml, crates/transport-nats/src/lib.rs, crates/transport/Cargo.toml, crates/transport/src/lib.rs, tests/integration.rs
- get rid of `async_trait` usage where possible
- simplify trait bounds
- prefer stack pinning
=> refactor: simplify type bounds

.github/dependabot.yml
Since there's a Go version included in the repository, it feels like it's worth keeping Dependabot's eyes on the modules that are included.
=> ci: Add Go modules updates via dependabot

tests/go/integration_test.go
Since I [noticed this](https://github.com/wrpc/wrpc/pull/52#discussion_r1598938398) while looking through #52, I figured I should just submit a PR to fix it :)
=> chore: Correct sync-server to async-server in test failure message

Cargo.lock, Cargo.toml, crates/runtime-wasmtime/src/lib.rs
sync with latest changes in https://github.com/WebAssembly/component-model/pull/336
=> sync codec with latest spec changes

crates/transport-legacy/src/lib.rs, crates/wit-bindgen-rust/src/interface.rs, crates/wit-bindgen-rust/tests/codegen.rs, tests/rust.rs
Closes #15. This PR implements resource support by representing resources as opaque handles. The handles are implemented as lists of bytes wrapped `ResourceOwn<T>` and `ResourceBorrow<T>` as outlined in #101.
This PR will supersede #82. This was implemented on new branch due to the significant differences between the opaque handle based approach for representing resources used here vs #82's approach that took a much more prescriptive approach to resource handling.
An example of resources being used with wRPC can be founding in the `rust_bindgen` test case in `tests/rust.rs`.
Other than revisions, I believe the main todo item left for this is to decide how to handle drops. I'm a little unsure if resource handlers should be forced to serve a `drop` method that clients can call, or if wRPC …
=> feat(wit-bindgen-rust) Implement resource handle support for `wit-bindgen-wrpc`

Cargo.lock, Cargo.toml, crates/runtime-wasmtime/src/lib.rs, crates/transport-nats/src/lib.rs, crates/transport-quic/src/lib.rs, crates/transport/Cargo.toml, crates/transport/src/lib.rs, crates/transport/src/value.rs, crates/wasmtime-nats-cli/src/lib.rs, src/lib.rs, tests/common/mod.rs, tests/go.rs, tests/rust.rs
- Remove associated `Error` types, and use `anyhow::Error` in `wrpc_transport` traits to simplify downstream usage. I really wish there was a nicer way to handle this and `std::io::Error` is a real pain to use in this context
- Add `ValueEncoder` and `ValueDecoder` drafts, the implementations will have to be expanded, but the idea is that users of `wrpc_transport` will implement `Encoder` and `Decoder` on these structs
=> feat(transport): add value codec

crates/runtime-wasmtime/src/lib.rs, crates/transport-nats/src/lib.rs, crates/transport-quic/src/lib.rs, crates/transport-quic/tests/loopback.rs, crates/transport/src/lib.rs, tests/rust.rs
Unfortunately, plain `&[&[Option<usize>]]` path bounds do not accept `Arc<[Arc<[Option<usize>]>]>` values, which users would likely use, especially in dynamic use cases. On top of that, lack of `'static` lifetime on the stream returned by `serve` prevents it from being passed into e.g. `tokio::spawn`.
Rework trait bounds to address these issues.
Thanks @luk3ark for reporting!
=> fix(transport): rework trait bounds

Cargo.lock, crates/transport-quic/src/lib.rs, crates/transport/src/lib.rs, crates/transport/src/value.rs, tests/rust.rs
Refs https://github.com/bytecodealliance/wrpc/issues/94#issuecomment-2144905193
Rework `invoke_values` and `serve_values` to accept much-more-generic `Encode` and `Decode`, which should be quite simple to implement for custom types.
Still need to iron out stream and future transfer
=> feat(transport): add `Encode` and `Decode` traits

crates/wit-bindgen-go/src/interface.rs
Make sure LEB128 decoding reads up to certain
number of bytes, which is specified based on the type.
This prevents the decoder reading the stream infinitely.
=> fix(win-bindgen-go): fix leb128 decoding

Cargo.lock, Cargo.toml, crates/introspect/Cargo.toml, crates/runtime-wasmtime/Cargo.toml, crates/test-helpers/codegen-macro/Cargo.toml, crates/transport/Cargo.toml, crates/wit-bindgen-go/Cargo.toml, crates/wit-bindgen/Cargo.toml, crates/wit-bindgen/src/examples/_1_interface_imports.rs, crates/wit-bindgen/src/examples/_2_imported_resources.rs, crates/wit-bindgen/src/examples/_3_world_exports.rs, crates/wit-bindgen/src/examples/_4_exported_resources.rs, crates/wit-bindgen/src/lib.rs
Switch to a nats fork published at https://docs.rs/async-nats-wrpc/latest/async_nats_wrpc/ while https://github.com/nats-io/nats.rs/pull/1267 is in review
=> chore: release

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/introspect/Cargo.toml, crates/runtime-wasmtime/Cargo.toml, crates/transport-nats/Cargo.toml, crates/transport-quic/Cargo.toml, crates/transport/Cargo.toml, crates/wasmtime-nats-cli/Cargo.toml, crates/wit-bindgen-go/Cargo.toml, crates/wit-bindgen-rust-macro/Cargo.toml, crates/wit-bindgen-rust/Cargo.toml, crates/wit-bindgen/Cargo.toml
a few last-minute dep updates and update of the workspace crate versions
held off the wasmtime 23 update due to https://github.com/bytecodealliance/wasmtime/pull/8786, which will require a bit more looking into to integrate in wRPC and downstream crates
=> chore(rust): update crates

examples/rust/complex-component-server/src/lib.rs
Update `bar: func(v: borrow<foo>) -> string` server implementation to call `Foo::bar(&self)` vs returning a static string.
=> examples/rust: complex impl demonstrates use of borrow

Cargo.toml
I noticed this was pointing to `wrpc/wrpc` still, and while GitHub handles that correctly, it would probably be better to just correct the location.
=> chore: Update crate homepage and repository

src/bin/wit-bindgen-wrpc.rs
`eprintln!` feels more appropriate here, especially in cases where other tools may be calling into `wit-bindgen-wrpc`.
=> fix(wit-bindgen-wrpc): Use eprintln instead of println for output

go/nats/client.go
We are leaving subscriptions open in 2 situations:
- Handshake: Missing Unsubscribe
- When `streamWriter` hands off a subscription to `indexedStreamWriter`: The Unsubscribe codepath is only in `streamWriter` via the `Close` method
This PR adds the missing `Unsubscribe` for handshakes, and makes so subscriptions handed of to `indexedStreamWriter` are closed by `streamWriter` during its `Close` call.
=> fix(go): Closing nats subscriptions

go/nats/client.go
- Remove usage of `.errors` channel removed in latest wRPC-over-NATS versions
- Remove `indexedStreamReader` abstraction, instead just use `streamReader`
- Count references to nested subscriptions and unsub only once all of them are dropped (possibly fixes issue originally reported in #214, still getting there)
cc @lxfontes
=> feat(go-nats): remove error channel and `indexedStreamReader`

crates/wit-bindgen-rust/src/interface.rs, tests/go.rs, tests/go/sync.go, tests/go/sync_test.go, tests/wit/test.wit
This commit fixes a bug which manifests itself when decoding a list of enums that may have separate internal decoder objects to use.
The issue is that storing the internal state inside the bindgen'd `Decoder` becomes a problem on the *second* (or subsequent) elements of a list of the given enum.
Given a `vec![SomeEnum::X, SomeEnum::Y]` the saved "state" for the first becomes the first decoder (i.e. the decoder for `SomeEnum::X`). When it comes time to parse the discriminant and bytes for `Y` the existence of the `state` causes a short circuit.
As the (wrong) decoder will generally try to process some bytes, you lose bytes from the input and then bytes are left over at the next attempt to decode (and then an error occurs). How this manifests is obviously specific to the enum, (wrong) …
=> fix(wit-bindgen-wrpc): clear out variant decoder internal state after use

go/nats/client.go
This PR adds a new function `NewClientWithQueueGroup` to the wRPC Go NATS client that, when a queue group is provided, will serve on a queue group rather than just a regular subscribe. This will allow users of the NATS client to run multiple services that serve the same functionality without duplication.
I could've just added this to the `NewClient` function, but I figured I'd avoid the breaking change there and simply add another constructor. Open to changing this back if desired
=> feat(go)!: allow serving with queue group

Cargo.lock, Cargo.toml, crates/transport-nats/src/lib.rs
https://github.com/nats-io/nats.rs/pull/1267
=> feat(rs-nats): switch to new `PublishMessage` sink

crates/transport/src/value.rs, tests/rust.rs
Refs #317 
@thomastaylor312 could you confirm that this addresses the issue?
=> fix(transport): use `ListDecoder` for lists of results and options

crates/wit-bindgen-go/src/interface.rs
While generating bindings I was greeted with a bunch of warnings about missing keys, so this adds the`instance` key to the places where it was missing:
```shell
bindings/exports/wrpc/keyvalue/store/bindings.wrpc.go:639:123: slog.WarnContext arg "err" should be a string or a slog.Attr (possible missing key or value)
bindings/exports/wrpc/keyvalue/store/bindings.wrpc.go:648:109: slog.WarnContext arg "err" should be a string or a slog.Attr (possible missing key or value)
bindings/exports/wrpc/keyvalue/store/bindings.wrpc.go:655:128: slog.ErrorContext arg "err" should be a string or a slog.Attr (possible missing key or value)
bindings/exports/wrpc/keyvalue/store/bindings.wrpc.go:662:141: slog.WarnContext arg "err" should be a string or a slog.Attr (possible missing key or value)
...
```
=> fix(wit-bindgen-go): Add missing 'instance' key to slog statements

Cargo.toml
In order to make the rust-url compatible with no_std, the crate needs to introduce a `std` feature and make it default. See https://github.com/servo/rust-url/pull/831.
To reduce impact, downstream libraries should leave url's default features enabled (no other features are currently `default`).
=> Enable default features for url crate

.github/workflows/wrpc.yml
Apparently, `cargo pkgid` uses `@` as separator for workspace subcrate versions and `#` for the root crate. TIL
=> ci: use `#` as version separator for root crate

Cargo.lock, Cargo.toml, crates/transport-nats/Cargo.toml, crates/transport-nats/src/lib.rs, tests/rust.rs
This ensures that clients are notified early of connection drop, effectively this is "connection reset by peer"
cc @thomastaylor312
=> fix(rs-nats): close streams on drop

Cargo.lock, Cargo.toml, crates/transport-quic/src/lib.rs, crates/transport/Cargo.toml, crates/transport/src/frame/codec.rs, crates/transport/src/frame/conn/accept.rs, crates/transport/src/frame/conn/client.rs, crates/transport/src/frame/conn/mod.rs, crates/transport/src/frame/conn/server.rs, crates/transport/src/frame/mod.rs, crates/transport/src/frame/tcp.rs, crates/transport/src/frame/unix.rs, tests/rust.rs
Implement a framed transport providing multiplexing to simple byte streams.
Include TCP and Unix socket implementations built on top of the same abstraction
Closes #9
=> feat(rs-transport): implement framed transport over TCP and UDS

crates/transport/src/value.rs, flake.nix
If the receiver is closed, then the data, even though received, can never reach the other end. Simply discard it and log at debug
=> fix(transport): discard async data if receiver is closed

Cargo.lock, crates/transport-nats/Cargo.toml, crates/transport-nats/src/lib.rs
Keep the I/O task around for as long as subscribers and writers are in use
=> fix(nats): prevent I/O task from being dropped prematurely

Cargo.lock, Cargo.toml, crates/test/Cargo.toml, crates/test/src/lib.rs, crates/transport-web/Cargo.toml, crates/transport-web/src/lib.rs, crates/transport-web/tests/loopback.rs, crates/transport/src/frame/conn/mod.rs, crates/transport/src/serve.rs, examples/rust/hello-tcp-server/src/main.rs, examples/rust/hello-web-client/Cargo.toml, examples/rust/hello-web-client/src/main.rs, examples/rust/hello-web-server/Cargo.toml, examples/rust/hello-web-server/src/main.rs, examples/web/rust/Cargo.toml, examples/web/rust/index.html, examples/web/rust/src/main.rs
`wtransport` seems to be better maintained and easier to get started with
added a begging of a very simple in-browser demo
=> feat(webtransport): rework with `wtransport`

examples/rust/hello-nats-server/src/main.rs, examples/rust/hello-tcp-server/src/main.rs, examples/rust/hello-web-server/src/main.rs, examples/rust/streams-nats-server/src/main.rs, examples/rust/wasi-keyvalue-nats-server/src/main.rs, examples/rust/wasi-keyvalue-tcp-server/src/main.rs
Show best-practice serving method, which maximizes throughput
=> chore(examples): use consistent serving method
