bytecodealliance/wrpc

- Cargo.lock
- Cargo.toml
- crates/transport/Cargo.toml
- crates/transport/src/lib.rs
Add a test for async impl trait lifetime bug workaround https://github.com/rust-lang/rust/issues/34511#issuecomment-373423999
> chore: add impl trait compiler bug test

- Cargo.lock
- Cargo.toml
- crates/interface-blobstore/Cargo.toml
- crates/interface-blobstore/src/lib.rs
- crates/interface-http/Cargo.toml
- crates/interface-http/src/lib.rs
- crates/interface-keyvalue/Cargo.toml
- crates/interface-keyvalue/src/lib.rs
- crates/runtime-wasmtime/Cargo.toml
- crates/transport-nats/Cargo.toml
- crates/transport-nats/src/lib.rs
- crates/transport/Cargo.toml
- crates/transport/src/lib.rs
> feat(transport): add compiler-lifetime-friendly serve API

- Cargo.lock
- crates/interface-http/wit/http.wit
- examples/go/http-outgoing-nats-server/main.go
- examples/rust/http-outgoing-nats-client/Cargo.toml
- examples/rust/http-outgoing-nats-client/src/main.rs
- go/client.go
- go/codec.go
- go/interface/http/interface.go
- go/interface/http/outgoing_handler/bindings.go
- go/interface/http/types/bindings.go
- go/nats/client.go
- go/subscriber.go
- go/util.go
This is just a first, incomplete draft of what an upcoming bindings generator would generate
> feat(go): add HTTP interface support

- Cargo.lock
- Cargo.toml
- crates/cli/Cargo.toml
- crates/interface-blobstore/Cargo.toml
- crates/interface-http/Cargo.toml
- crates/introspect/Cargo.toml
- crates/introspect/src/lib.rs
- crates/runtime-wasmtime/Cargo.toml
- crates/transport-nats/Cargo.toml
- crates/transport/Cargo.toml
- crates/types/Cargo.toml
- crates/wasmtime-nats-cli/Cargo.toml
- crates/wit-bindgen-go/Cargo.toml
- crates/wit-bindgen-go/src/interface.rs
- crates/wit-bindgen-rust-macro/Cargo.toml
- crates/wit-bindgen-rust/Cargo.toml
- crates/wit-bindgen/Cargo.toml
Refs https://github.com/wrpc/wrpc/pull/82#discussion_r1611500823
> feat(introspect): extract `wrpc-introspect` crate

- ADOPTERS.md
- flake.nix
> doc: add `ADOPTERS.md`

- CONTRIBUTING.md
> doc: add `CONTRIBUTING.md`

- SECURITY.md
> doc: add `SECURITY.md`

- README.md
> doc: identify as Bytecode Alliance hosted project

- CODE_OF_CONDUCT.md
https://github.com/wrpc/wrpc/issues/105
> doc: add CoC

- Cargo.lock
- Cargo.toml
- crates/runtime-wasmtime/src/lib.rs
- crates/transport-nats/src/lib.rs
- crates/transport-quic/Cargo.toml
- crates/transport-quic/src/lib.rs
- crates/transport-quic/tests/loopback.rs
- crates/transport/Cargo.toml
- crates/transport/src/frame.rs
- crates/transport/src/lib.rs
- crates/wit-bindgen-rust/src/interface.rs
Implement a QUIC transport, this also includes a wRPC transport framing, which is unused for this transport, but could be for transports, that do not have native multiplexing like QUIC does
> feat: implement QUIC transport

- Cargo.lock
- crates/runtime-wasmtime/Cargo.toml
- crates/runtime-wasmtime/src/lib.rs
- crates/transport/src/lib.rs
- crates/wasmtime-nats-cli/src/lib.rs
- Backported the granular API from https://github.com/bytecodealliance/wasmtime/pull/8737
- Aligned stream and resource implementation with current design
> feat(runtime-wasmtime): add granular linking API

- Cargo.lock
- Cargo.toml
- crates/test-helpers/src/lib.rs
- crates/wasmtime-nats-cli/src/lib.rs
- crates/wit-bindgen-go/src/interface.rs
- crates/wit-bindgen-go/src/lib.rs
- crates/wit-bindgen-rust-macro/Cargo.toml
- crates/wit-bindgen-rust-macro/src/lib.rs
- crates/wit-bindgen-rust/Cargo.toml
- crates/wit-bindgen-rust/src/lib.rs
- crates/wit-bindgen-rust/tests/codegen.rs
- crates/wit-bindgen/Cargo.toml
- crates/wit-bindgen/src/examples/_1_interface_imports.rs
- crates/wit-bindgen/src/examples/_3_world_exports.rs
- crates/wit-bindgen/src/lib.rs
- examples/rust/complex-component-client/src/main.rs
- examples/rust/hello-component-client/src/main.rs
- examples/rust/hello-nats-client/src/main.rs
- examples/rust/hello-nats-server/src/main.rs
- examples/rust/wasi-keyvalue-component-client/src/main.rs
- src/bin/wit-bindgen-wrpc.rs
- tests/codegen/flags.wit
- tests/codegen/fully-qualified-java-address.wit
- tests/codegen/issue929-no-export.wit
- tests/codegen/issue929-no-import.wit
- tests/codegen/issue929-only-methods.wit
- tests/codegen/issue929.wit
This includes sync to https://github.com/bytecodealliance/wit-bindgen/releases/tag/v0.27.0
> chore: update deps

- Cargo.lock
- Cargo.toml
- crates/runtime-wasmtime/Cargo.toml
- crates/runtime-wasmtime/src/lib.rs
- crates/transport/Cargo.toml
- crates/transport/src/invoke.rs
- crates/wasmtime-nats-cli/Cargo.toml
- crates/wasmtime-nats-cli/src/lib.rs
- examples/rust/complex-component-client/src/main.rs
- examples/rust/complex-component-server/Cargo.toml
- examples/rust/complex-component-server/src/lib.rs
- examples/rust/complex-component-server/wit/deps.lock
- examples/rust/complex-component-server/wit/deps.toml
- examples/rust/complex-component-server/wit/deps/complex/complex.wit
- examples/rust/complex-component-server/wit/world.wit
components can now import and export resources
> feat(rust): add full resource support

- Cargo.lock
- Cargo.toml
- crates/wit-bindgen-rust-macro/Cargo.toml
- crates/wit-bindgen-rust/Cargo.toml
- crates/wit-bindgen/Cargo.toml
> chore: bump crate version

- README.md
Add a quickstart guide in README.md.
> docs(readme): add quickstart guide

- README.md
- rust-toolchain.toml
> doc: expand `hello` example

- README.md
Fixup quickstart formatting, which I broke in #300
> doc: fix formatting

- Cargo.lock
- crates/pack/Cargo.toml
- crates/pack/src/lib.rs
Stopgap solution until https://github.com/bytecodealliance/wrpc/issues/25 is complete
cc @protochron
> feat(pack): add flat byte buffer stopgap crate

- Cargo.lock
- Cargo.toml
- crates/runtime-wasmtime/Cargo.toml
- crates/runtime-wasmtime/src/lib.rs
- crates/wasmtime-nats-cli/Cargo.toml
refs https://github.com/bytecodealliance/wasmtime/pull/9129
> feat: update to wasmtime 25

- Cargo.lock
- Cargo.toml
> merge: wit-bindgen 0.33

- Cargo.lock
- Cargo.toml
- crates/runtime-wasmtime/src/lib.rs
- crates/transport-nats/src/lib.rs
- crates/transport-quic/src/lib.rs
- crates/transport/Cargo.toml
- crates/transport/src/frame/conn/client.rs
- crates/transport/src/frame/conn/server.rs
- crates/transport/src/frame/tcp/tokio.rs
- crates/transport/src/frame/unix.rs
- crates/transport/src/invoke.rs
- crates/transport/src/value.rs
- crates/wasmtime-cli/src/tcp.rs
- examples/rust/hello-tcp-server/src/main.rs
- examples/rust/wasi-keyvalue-tcp-server/src/main.rs
Refs https://github.com/wasmCloud/wasmCloud/issues/3362
> fix(transport): do not panic on invalid future decoder usage

- Cargo.lock
- Cargo.toml
- crates/transport-nats/Cargo.toml
- crates/transport-nats/src/lib.rs
> feat(nats): support two `async-nats` versions

- Cargo.lock
- Cargo.toml
- merge wit-bindgen 0.34
- update rust deps
> merge: wit-bindgen 0.34

- examples/web/ui/index.html
Thanks @macovedj for getting it set up!
> feat(kv-web): add `wa.dev` interface link

- README.md
refs #168 
The badges are now broken and have been for a while, so removing them
> doc: remove broken badges

- Cargo.lock
- Cargo.toml
- crates/cli/Cargo.toml
- crates/transport-nats/Cargo.toml
- crates/transport-nats/src/lib.rs
- crates/wasmtime-cli/Cargo.toml
- examples/rust/hello-nats-client/Cargo.toml
- examples/rust/hello-nats-server/Cargo.toml
- examples/rust/streams-nats-client/Cargo.toml
- examples/rust/streams-nats-server/Cargo.toml
- examples/rust/wasi-keyvalue-nats-client/Cargo.toml
- examples/rust/wasi-keyvalue-nats-server/Cargo.toml
- examples/web/rust/Cargo.toml
> build: update `async-nats`

- crates/wit-bindgen-rust/src/interface.rs
- crates/wit-bindgen-rust/src/lib.rs
- tests/codegen/variants.wit
https://github.com/bytecodealliance/wit-bindgen/compare/v0.35.0...v0.36.0
> merge: `wit-bindgen` 0.36

- .github/workflows/nix.yml
- .github/workflows/scorecard.yml
- .github/workflows/update.yml
- .github/workflows/wrpc.yml
https://github.com/actions/runner-images/issues/10443
> ci: pin ubuntu image versions

- Cargo.lock
- Cargo.toml
- benches/bench.rs
- crates/runtime-wasmtime/src/lib.rs
- crates/wasmtime-cli/src/lib.rs
Refs https://github.com/bytecodealliance/wasmtime/pull/10036
Refs https://github.com/bytecodealliance/wasmtime/pull/9618
> chore: update to Wasmtime 30
